### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by CNK001** [GawainLynch/bolt-extension-rateit#5]
Could you tell me, how I can  use it? I install this extension to bolt, but I have only simple slider, not stars..

**Comment by GawainLynch** [comment]
That sounds like the JavaScript isn't loading properly.

Can you check that there are no 404 errors in your browser console.

**Comment by CNK001** [comment]
Ok, when I changed template to "base-2014" it works in record.twig! :)
How can I use it in listing.twig template?

Regards

**Comment by GawainLynch** [comment]
Ah! My guess is that `base-2014` loads jQuery, but you theme doesn't… try that.

You should get errors in the browser developer console that will tell you.

**Comment by CNK001** [comment]
I cleaned everything in Cloudflare and cleaned browser cache and now it works on my theme :)
But it works only in single entry, it's possible to use it on list of entries?

**Comment by GawainLynch** [comment]
Not currently… Someone was going to have an attempt to do it a while ago, but noting appeared.

I am not sure it's that hard to implement, just not something I have had time to do myself.
